#! /usr/bin/env php

<?php

use Acme\CreditCardApplication;

require 'vendor/autoload.php';

//This will be a one command application that will run all
//sub-commands based on input from a file.
$app = new CreditCardApplication();
$app->run();
