#! /usr/bin/env php

<?php

use Acme\Command;
use Acme\CreditCardApplication;
use Acme\DatabaseConnection;
use Symfony\Component\Console\Application;
require 'vendor/autoload.php';

//This will be a one command application that will run all
//sub-commands based on input from a file.
$app = new CreditCardApplication();
$app->run();
